apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orchestrai-pod-exec-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: orchestrai-pod-exec-clusterrole
subjects:
- kind: ServiceAccount
  name: orchestrai-sa
  namespace: default

