apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrai-sa
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orchestrai-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrai-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: orchestrai-sa
    namespace: default
roleRef:
  kind: Role
  name: orchestrai-role
  apiGroup: rbac.authorization.k8s.io

