apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orchestrai-pod-exec-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrai-pod-exec-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orchestrai-pod-exec-role
subjects:
  - kind: ServiceAccount
    name: 434296769439-compute
    namespace: default

