apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrai-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: orchestrai-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrai-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: "105578291885468670827"
    namespace: default
roleRef:
  kind: Role
  name: orchestrai-role
  apiGroup: rbac.authorization.k8s.io

