kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: orchestrai-pvc-role
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims", "pods"]  # <-- ajoute "pods" ici
  verbs: ["get", "list", "watch", "create", "delete", "update"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: orchestrai-pvc-access-binding
subjects:
- kind: User
  name: "105578291885468670827"
roleRef:
  kind: ClusterRole
  name: orchestrai-pvc-role
  apiGroup: rbac.authorization.k8s.io

