# --- rbac-config.yaml ---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrai-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: orchestrai-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrai-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    # ✅ CORRECTION ICI
    name: orchestrai-sa
    namespace: default
roleRef:
  kind: Role
  name: orchestrai-role
  apiGroup: rbac.authorization.k8s.io
