apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: development-agent
  template:
    metadata:
      labels:
        app: development-agent
    spec:
      containers:
      - name: development-agent
        image: gcr.io/PROJECT_ID/development-agent:latest
        ports:
        - containerPort: 8080
        env:
        - name: INTERNAL_URL
          value: http://development-agent.default.svc.cluster.local:8080
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /app/credentials.json
        volumeMounts:
        - name: code-volume
          mountPath: /app
      volumes:
      - name: code-volume
        persistentVolumeClaim:
          claimName: development-agent-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: development-agent
spec:
  type: ClusterIP
  selector:
    app: development-agent
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: development-agent-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
