apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-agent
  labels:
    app: development-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: development-agent
  template:
    metadata:
      labels:
        app: development-agent
    spec:
      serviceAccountName: orchestrai-sa
      containers:
        - name: development-agent
          # La variable ${IMAGE} sera remplacée par le script
          image: ${IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: AGENT_NAME
              value: "DevelopmentAgentGKEv2" 
            - name: GRA_PUBLIC_URL
              value: "${GRA_PUBLIC_URL}"
            - name: KUBERNETES_NAMESPACE
              value: "${KUBERNETES_NAMESPACE}"

            # ✅ VARIABLES AJOUTÉES POUR L'ENREGISTREMENT
            - name: PUBLIC_URL
              value: "http://development-agent.${KUBERNETES_NAMESPACE}.svc.cluster.local:80"
            - name: INTERNAL_URL
              value: "http://development-agent.${KUBERNETES_NAMESPACE}.svc.cluster.local:8080"
            
            # URL pour trouver l'Environment Manager
            - name: ENV_MANAGER_URL
              value: "http://environment-manager.${KUBERNETES_NAMESPACE}.svc.cluster.local:80"

            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/sa-key.json"
            
            # Variables GCP pour corriger le WARNING du client LLM
            - name: GCP_PROJECT_ID
              value: "${PROJECT_ID}"
            - name: GCP_REGION
              value: "${GCP_REGION}"

          volumeMounts:
            - name: service-account-volume
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: service-account-volume
          secret:
            secretName: gcp-sa-key
---
apiVersion: v1
kind: Service
metadata:
  name: development-agent
  annotations:
    cloud.google.com/neg: '{"ingress":true}' 
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector:
    app: development-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer