apiVersion: apps/v1
kind: Deployment
metadata:
  name: environment-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: environment-manager
  template:
    metadata:
      labels:
        app: environment-manager
    spec:
      serviceAccountName: orchestrai-sa
      containers:
      - name: environment-manager
        image: gcr.io/PROJECT_ID/environment-manager:latest
        ports:
        - containerPort: 8080
        env:
        - name: INTERNAL_URL
          value: http://environment-manager.default.svc.cluster.local:8080
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /app/credentials.json
---
apiVersion: v1
kind: Service
metadata:
  name: environment-manager
spec:
  type: ClusterIP
  selector:
    app: environment-manager
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: environment-manager-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
