apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrai-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orchestrai-exec-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orchestrai-exec-rolebinding
subjects:
- kind: ServiceAccount
  name: orchestrai-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: orchestrai-exec-role
  apiGroup: rbac.authorization.k8s.io

